name: Preparar per producció
run-name: ${{ github.actor }} está pujant l'aplicació a PROD ✅

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenir el codi del repositori
        uses: actions/checkout@v4
      
      - name: scp a producció
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          scp -r -o StrictHostKeyChecking=no -i "~/prod_key.pem" -o UserKnownHostsFile=/dev/null -P 22 /home/aleiram/ghactions-aleiram19/* 
          ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a23aleminram/web/public_html/actions/
      
      - run: echo "📊 This job's status is ${{ job.status }}."